Railway Reservation/Controllers/TrainController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Plugins;
using Railway_Reservation.Data;
using Railway_Reservation.Models;

namespace Railway_Reservation.Controllers
{
    public class TrainController : Controller
    {
        private readonly ApplicationContext _context;
        public TrainController(ApplicationContext context)
        {
            _context = context;
        }
        
        public ActionResult Index()
        {
            var ListOfTrains = _context.Trains.ToList();
            return View(ListOfTrains);
        }       
        
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<Train>> Create(Train Trains)
        {
            if (ModelState.IsValid == true)
            {
                _context.Trains.Add(Trains);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                return BadRequest(ModelState);
            }

        }
    }
}

Railway Reservation/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Railway_Reservation.Data;
using Railway_Reservation.Models;

namespace Railway_Reservation.Controllers
{
    public class UserController : Controller
    {

        private readonly ApplicationContext _context;

        public UserController(ApplicationContext context)
        {
            _context = context;
        }

        public ActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<User>> Register(User Users)
        {
            if (ModelState.IsValid == true)
            {
                _context.Users.Add(Users);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Login));
            }
            return BadRequest(ModelState);
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<User>> Login(User Users)
        {
            var Record = await _context.Users.Where(o => o.Email == Users.Email && o.Password == Users.Password).FirstOrDefaultAsync();

            if (Record != null)
            {
                TempData["UserName"] = Record != null ? Record.FirstName + Record.LastName : string.Empty;
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController));
            }

            return View();
        }
        public IActionResult LoginPartial()
        {
            return PartialView("_LoginPartial");
        }


    }
}

Railway Reservation/Views/Shared/_Layout.cshtml
-<!DOCTYPE html>
<html lang="en">
@*<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Railway_Reservation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Railway_Reservation.styles.css" asp-append-version="true" />
    <link rel="icon" href="./favicon.ico" type="image/png">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="./js/fancybox/jquery.fancybox.css" type="text/css" media="screen" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css">
    <link href="~/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="~/css/animate.css" rel="stylesheet" type="text/css">
    @*<link rel="stylesheet" href="css/login.css">
</head>*@
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, maximum-scale=1">
    <title>RRS</title>
    <link  href="/Static/favicon.png" rel="icon" type="image/png">
    <link href="/Static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/Static/js/fancybox/jquery.fancybox.css" rel="stylesheet" type="text/css" media="screen" />
    <link href="/Static/css/style.css" rel="stylesheet" type="text/css">
    @*<link rel="stylesheet" href="/Static/css/login.css">*@
    @*<link href="/Static/css/stylee.css" rel="stylesheet" type="text/css">*@
    <link href="/Static/css/font-awesome.css" rel="stylesheet" type="text/css">
    <link href="/Static/css/animate.css" rel="stylesheet" type="text/css">

</head>
<body>
   @* <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Railway_Reservation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <header id="header_wrapper">
        <div class="container">
            <div class="header_box">
                <div class="logo"><a href="#"><img src="/Static/img/logo.png" alt="logo"></a></div>
                <nav class="navbar navbar-inverse" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="nav-toggle" class="navbar-toggle" data-toggle="collapse"
                                data-target="#main-nav">
                            <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div id="main-nav" class="collapse navbar-collapse navStyle">
                        <ul class="nav navbar-nav" id="mainNav">
                            <li  class="active"><a asp-controller="Home" asp-action="Index" class="scroll-link">Home</a></li>
                            <li><a href="train-booking.html" class="scroll-link">Book Tickets</a></li>
                            <li><a href="#aboutUs" class="scroll-link">About Us</a></li>
                            <li><a href="#service" class="scroll-link">Services</a></li>
                            <li><a asp-controller="Train" asp-action="Index">Train</a></li>
                            <li><a href="#clients" class="scroll-link">STATION</a></li>
                            <li><a href="#team" class="scroll-link">Team</a></li>
                            <li><a href="#contact" class="scroll-link">Contact</a></li>
                            <li><a asp-area="" asp-controller="User" asp-action="Register" class="scroll-link">Signup</a></li>
                            <li><a asp-area="" asp-controller="User" asp-action="Login" class="scroll-link">Login</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer_wrapper" id="contact">
        <div class="container">
            <section class="page_section contact" id="contact">
                <div class="contact_section">
                    <h2>Contact Us</h2>
                    <div class="row">
                        <div class="col-lg-4">
                        </div>
                        <div class="col-lg-4">
                        </div>
                        <div class="col-lg-4">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 wow fadeInLeft" style="color: #fff;">
                        <div class="contact_info">
                            <div class="detail">
                                <h4>UNIQUE Infoway</h4>
                                <p>104, Some street, Chennai</p>
                            </div>
                            <div class="detail">
                                <h4>call us</h4>
                                <p>+1 234 567890</p>
                            </div>
                            <div class="detail">
                                <h4>Email us</h4>
                                <p>support@sitename.com</p>
                            </div>
                        </div>



                        <ul class="social_links">
                            <li class="twitter animated bounceIn wow delay-02s">
                                <a  >
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li class="facebook animated bounceIn wow delay-03s">
                                <a  >
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li class="pinterest animated bounceIn wow delay-04s">
                                <a  >
                                    <i class="fa fa-pinterest"></i>
                                </a>
                            </li>
                            <li class="gplus animated bounceIn wow delay-05s">
                                <a  >
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-8 wow fadeInLeft delay-06s" style="color: #fff;">
                        <div class="form">
                            <input class="input-text" type="text" name="" value="Your Name *"
                                   onFocus="if(this.value==this.defaultValue)this.value='';"
                                   onBlur="if(this.value=='')this.value=this.defaultValue;">
                            <input class="input-text" type="text" name="" value="Your E-mail *"
                                   onFocus="if(this.value==this.defaultValue)this.value='';"
                                   onBlur="if(this.value=='')this.value=this.defaultValue;">
                            <textarea class="input-text text-area" cols="0" rows="0"
                                      onFocus="if(this.value==this.defaultValue)this.value='';"
                                      onBlur="if(this.value=='')this.value=this.defaultValue;">Your Message *</textarea>
                            <input class="input-btn" type="submit" value="send message">
                        </div>
                    </div>
                </div>
            </section>
        </div>
        <div class="container">
            <div class="footer_bottom">
                <span>
                    Copyright © 2021-2022,  by <a href="http://pdflibrary.pythonanywhere.com/">MAHABAHO</a>.
                </span>
            </div>
        </div>
    </footer>
    <script>
        /* Type-1 */
        $("#myCarousel").carousel({
            interval: 4000
        });

        $(".carousel .item").each(function () {
            var next = $(this).next();
            if (!next.length) {
                next = $(this).siblings(":first");
            }
            next.children(":first-child").clone().appendTo($(this));

            for (var i = 0; i < 2; i++) {
                next = next.next();
                if (!next.length) {
                    next = $(this).siblings(":first");
                }

                next.children(":first-child").clone().appendTo($(this));
            }
        });

    </script>
    @*<script src="/Static/lib/jquery/dist/jquery.min.js"></script>
    <script src="/static/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/site.js" asp-append-version="true"></script>*@
    <script  src="/Static/js/language_tran.js"></script>
    <script type="text/javascript" src="/Static/js/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="/Static/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/Static/js/jquery-scrolltofixed.js"></script>
    <script type="text/javascript" src="/Static/js/jquery.nav.js"></script>
    <script type="text/javascript" src="/Static/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="/Static/js/jquery.isotope.js"></script>
    <script src="/Static/js/fancybox/jquery.fancybox.pack.js" type="text/javascript"></script>
    <script type="text/javascript" src="/Static/js/wow.js"></script>
    <script type="text/javascript" src="/Static/js/custom.js"></script>
*    @await RenderSectionAsync("Script", required: false)

</body>
</html>